# Generated by Django 5.1.4 on 2025-01-03 20:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poliza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('vip', 'VIP'), ('premium', 'PREMIUM'), ('platinum', 'PLATINUM'), ('bronze', 'BRONZE'), ('basic', 'BASIC')], max_length=20)),
                ('price', models.FloatField()),
                ('duration', models.IntegerField(help_text='Duration of the poliza')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poliza.poliza')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['active'], name='ranges_rang_active_dcd5c0_idx'), models.Index(fields=['deleted_at'], name='ranges_rang_deleted_f3258c_idx')],
            },
        ),
    ]
